### ISSUE TITLE
Html element doesn't wrap text

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#136]
Hello Ionic Team.  I tried using the Html element, and put a few paragraphs.  But the content shows only one paragraph, and doesn't show all of the html information.

Please fix this when you have the chance.
Thanks

**Comment by Ionitron** [comment]
Greetings @shaulhadar!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
