### ISSUE TITLE
Select and Radio type input not working

### ISSUE THREAD

**Issue by razat2013** [driftyco/ionic-creator-issues#140]
I am trying to add form element with select and radio buttons, but there is no option for Giving options in select and radio buttons

**Comment by Ionitron** [comment]
Greetings @razat2013!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
