### ISSUE TITLE
Show loader to give response to the user when he perform some actions.

### ISSUE THREAD

**Issue by shamsher31** [driftyco/ionic-creator-issues#143]
Glad to use Ionic creator. It will be more elegant if the loader is display when user clicks or perform some action as the response is not so quick.

**Comment by Ionitron** [comment]
Greetings @shamsher31!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
