### ISSUE TITLE
Move image inside Card

### ISSUE THREAD

**Issue by erinni** [driftyco/ionic-creator-issues#199]
If you drag the IMAGE component inside the CARD is ok but 
1) you can't move an IMAGE from canvas (phone main screen) inside the CARD
2) you can drag an IMAGE from inside the CARD but you can't put it again inside the CARD.

**Comment by Ionitron** [comment]
Greetings @erinni!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
