### ISSUE TITLE
Choose device viewports and platforms

### ISSUE THREAD

**Issue by gregorypratt** [driftyco/ionic-creator-issues#2]
Feature request: Ability to choose device viewports and platforms to see if the code reacts as responsive as Ionic will allow

**Comment by Ionitron** [comment]
Greetings @gregorypratt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
