### ISSUE TITLE
In/Out navigation overview support

### ISSUE THREAD

**Issue by kfbishop** [driftyco/ionic-creator-issues#210]
Along the idea of a "site map" level storyboard, it would be great to have a av assistance view such that for my current view, I can easily see what views link to this view, and all the views that are linked from this view.  This allows for comprehension of utility views that are linked from multiple. The current Views list quickly get unwieldly after several pages are defined.

Here's a  
![sample mock-up](https://cloud.githubusercontent.com/assets/300008/7215540/1ce6bade-e5ab-11e4-82de-72d6a3a87490.png)

Clicking on any view focuses it in the center for editing, updating its possible from and to views.  This enables the current "Views" panel to just contain the hierarchy of its child elements.

**Comment by Ionitron** [comment]
Greetings @kfbishop!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
