### ISSUE TITLE
Views list should be collapsable and sorted alphabetically

### ISSUE THREAD

**Issue by kfbishop** [driftyco/ionic-creator-issues#211]
When there are more than a few pages, they become difficult to quickly locate.

Additionally, being able to collapse the current view will also ease navigation between views.

**Comment by Ionitron** [comment]
Greetings @kfbishop!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
