### ISSUE TITLE
Clicking header doesn't select current page

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#229]
Seems like I have to click the page name in the left pages list to see the page properties on the right.  I think this should work when you select the entire page also.  It gets selected, but doesn't show the properties on the right.

**Comment by matthewkremer** [comment]
You're talking about when you click the page and it highlights the entire thing, right? That seems to select and show the properties on the right just fine for me.

What browser are you using? Thanks!

**Comment by pmsteil** [comment]
Sorry, I was talking about clicking outside the page, so I am intending that nothing have focus :)

**Comment by matthewkremer** [comment]
I thought that's what you were talking about in #233?

**Comment by pmsteil** [comment]
Oops, sorry - ignore comment, I will remove that comment... got in a hurry.  

Here is a video of the issue:
http://screencast.com/t/gum9Vp7R1

**Comment by matthewkremer** [comment]
Hey @pmsteil, thanks for the video! Definitely helped me figure out what's going on. I think the issue is that you were clicking the header, which right now doesn't seem to be linked to any click events (although that's probably something we should add).

If you click the page body it should definitely select for you and show the properties on the right :smile:

**Comment by pmsteil** [comment]
Yes, that did work, thanks!
