### ISSUE TITLE
Need a Universal Header & Footer across all pages

### ISSUE THREAD

**Issue by mndotmail** [driftyco/ionic-creator-issues#241]
Hi Iconic team,

I am very much new to Iconic & JS / AnjularJS. 
My mobile app needs a universal Header & Footer across all the pages, except the Home page.
In WordPress, this is possible by calling wp-header.php (https://codex.wordpress.org/Function_Reference/get_header)

As far I learnt Iconic, I have to write the Header / Footer for every page. How can I achieve universal header / footer.
Looking forward.

**Comment by matthewkremer** [comment]
Greetings @mndotmail !

It seems like this issue is requesting usage help, rather than an actual error with Ionic Creator.

This GitHub issue tracker is used to track Creator features, problems, and development.

If you wish to get help using the framework itself, the recommended place is the forum (http://forum.ionicframework.com/). There are many people there who would be happy to offer sage advice.

Have a good one!
Matt

**Comment by mndotmail** [comment]
Thanks @matthewkremer.
I will get the help from forums.
