### ISSUE TITLE
Can't place a button within a card inside a list

### ISSUE THREAD

**Issue by cesarlugosis** [driftyco/ionic-creator-issues#286]
In the previous version of Ionic Creator, I included an list-item-with-thumbnail within a list-item and then I added a button within the list-item-with-thumbnail. Now on this version I tried to do the same and it doesn't let me drag a button inside a list-item-with-thumbnail within a list-item, it places the button outside the list when I try to do that.

**Comment by Ionitron** [comment]
Greetings @cesarlugosis!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
