### ISSUE TITLE
Import/Export design to XML or JSON

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#290]
Would be nice if one could export to XML or JSON the whole visual tree. That would make one feel safer in case some corruption happens to the project, especially since I don't see any Undo/Redo o/History and/or Online Backups/Restore recent version (like in Dropbox) functionality

I understand though you may have to then be extra careful to support importing of previously saved files (backwards compatibility for the file loader code) as you add more features to the creator, but it could be done. 

Compatibility the other way around (forward compatibility) isn't needed (load newer saved files at older version of creator), since one always uses the latest version of creator online app (would be needed only if you release standalone creator app, but could have that check/autoupdate with newer version and refuse to open newer files [have some version stamp in the file] till updated)

**Comment by Ionitron** [comment]
Greetings @birbilis!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
