### ISSUE TITLE
Page/state navigation diagram

### ISSUE THREAD

**Issue by gregorypratt** [driftyco/ionic-creator-issues#3]
An interactive state flow diagram to visualise and edit the navigation of your app...

**Comment by Ionitron** [comment]
Greetings @gregorypratt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
