### ISSUE TITLE
Show Library Versions

### ISSUE THREAD

**Issue by webonix** [driftyco/ionic-creator-issues#31]
In the slide out menu (right side menu)
would be good to see versions of libraries used
eg
* Ionic
* Angular
* Creator?
 * that can be used to view releases showing what issues were closed / resolved

**Comment by Ionitron** [comment]
Greetings @webonix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
