### ISSUE TITLE
the componets tabs

### ISSUE THREAD

**Issue by peteryes** [driftyco/ionic-creator-issues#32]
I have a surface pro3 the components tabs are showing across the surface not on the left

**Comment by Ionitron** [comment]
Greetings @peteryes!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
