### ISSUE TITLE
Support for Ionic Directives API

### ISSUE THREAD

**Issue by webonix** [driftyco/ionic-creator-issues#37]
Is the plan to support all ion APIs?
eg
* http://ionicframework.com/docs/api/directive/ionList/
* http://ionicframework.com/docs/api/directive/ionTabs/

That is, will the property inspector be able to set all of these?
```
<ion-list ng-controller="MyCtrl"
          show-delete="shouldShowDelete"
          show-reorder="shouldShowReorder"
          can-swipe="listCanSwipe">
  <ion-item ng-repeat="item in items"
            class="item-thumbnail-left">
```

Currently, there are no properties for list, only list-item.

Will it be possible to added components into a list item?
eg button or image

**Comment by Ionitron** [comment]
Greetings @webonix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
