### ISSUE TITLE
ionic color scheme creator

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic-creator-issues#51]
It would be really exciting to have a color scheme generator (like the one bvootstrap has) for ionic along with ```ionic-creator```.

Hope we will get this soon too.

**Comment by Ionitron** [comment]
Greetings @programming-kid!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
