### ISSUE TITLE
Feature Request: Grid Support

### ISSUE THREAD

**Issue by sicsol** [driftyco/ionic-creator-issues#61]
Ability to add grids for layout enhancements

**Comment by johnwoolee** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @sicsol!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
