### ISSUE TITLE
Feature Request: Content area padding adjustments

### ISSUE THREAD

**Issue by sicsol** [driftyco/ionic-creator-issues#62]
Ability to adjust/remove the padding in the page content area so we can do 'full width' layouts.

**Comment by matthewkremer** [comment]
I've added a padding toggle to both pages and content boxes (in tabbed pages), so you should be able to turn the padding off now for full-width layouts.

Since padding is a core style in Ionic, if you actually want to change padding it's recommended that you do so in the Ionic config when downloading your project.

Thanks! :+1:
