### ISSUE TITLE
Feature Request: Slide Box support

### ISSUE THREAD

**Issue by sicsol** [driftyco/ionic-creator-issues#63]
It would be great to offer support for slidebox

**Comment by Ionitron** [comment]
Greetings @sicsol!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
