### ISSUE TITLE
chromium on linux overrides 'text/plain' - bug

### ISSUE THREAD

**Issue by patlux** [driftyco/ionic-creator-issues#67]
see:

![creator](https://cloud.githubusercontent.com/assets/4481570/4760296/c07621c8-5aee-11e4-947d-a0713cc9f883.jpg)

issue tracker on code.google: https://code.google.com/p/chromium/issues/detail?id=332579

please fix it!

workaround: just create an own type like 'text/componentType' to datatransfer and get it on dropevent.

**Comment by Ionitron** [comment]
Greetings @patlux!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
