### ISSUE TITLE
Selecting button type "button-icon button-block" and style other than "button-stable" or "button-light" does not display button title and appropriate colors

### ISSUE THREAD

**Issue by vtirta** [driftyco/ionic-creator-issues#72]

**Comment by Ionitron** [comment]
Greetings @vtirta!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
