### ISSUE TITLE
button-icon button-block isn't visible

### ISSUE THREAD

**Issue by WindSekirun** [driftyco/ionic-creator-issues#83]
![2014-11-01 11 48 23](https://cloud.githubusercontent.com/assets/3054645/4870568/961051e0-6171-11e4-9732-be990f36fcf3.png)

other options(button-block, button-clear) is working, but i can't see button-icon button-block.

I use Ionic Creator in OS X Yosemite, Chrome.

**Comment by Ionitron** [comment]
Greetings @WindSekirun!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
