### ISSUE TITLE
Button loses focus on new page created

### ISSUE THREAD

**Issue by igorcosta** [driftyco/ionic-creator-issues#85]
I just record my first access to the ionic creator and while recording you will see the chanllenge to make it work on some buttons with recently created page.

https://www.youtube.com/watch?v=RvCUIiAupJ8

**Comment by Ionitron** [comment]
Greetings @igorcosta!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
