### ISSUE TITLE
Page close button in preview is rendered behind container

### ISSUE THREAD

**Issue by adammatthewsmith** [driftyco/ionic-creator-issues#89]
The icon for deleting a page that is shown on the page itself and not in the right side toolbar is 75% hidden behind the container for the page (the gray frame).  This makes the close button look almost like an arrow that could indicate an expand operation on the preview.  

Chrome Version 38.0.2125.111 m

**Comment by Ionitron** [comment]
Greetings @adammatthewsmith!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
