### ISSUE TITLE
Feature request: Inline components

### ISSUE THREAD

**Issue by mcampo** [driftyco/ionic-creator-issues#94]
It would be nice to have components that act as inline elements inside a container.

**Comment by Ionitron** [comment]
Greetings @mcampo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
