### ISSUE TITLE
Issues recovering the password if you don't have forum account

### ISSUE THREAD

**Issue by Foxandxss** [driftyco/ionic-creator-issues#97]
I had a chat with @mhartington about a issue I had with my account. Let put a case.

New user (John), no account in any part of ionic.

John gets an creator invite, he goes to the creator url, creates a new account and he works there.

Tomorrow John forgets his password so he clicks on recover password and that sends you to the forum. There you put your email and it doesn't exist (because John never activated his forum account) so you get no recovery email.

If John remember his username (I didn't) he can put it and get an email.

As today, the recovery email sent by forum gives you a link which gives an error 500 (activation link still gives 500).

So the **TL;DR** here is: If you don't have an activated account on the forum, you can't use your email to recover your account and if you don't remember your username (I didn't) you are screwed.

**Comment by Ionitron** [comment]
Greetings @Foxandxss!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
